name: nfc_e_wallet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
  cupertino_icons: ^1.0.2
  get_it: any
  meta: any
  bloc: any
  animated_bottom_navigation_bar: ^1.1.0
  circular_reveal_animation: ^2.0.1
  barcode_scan2: ^4.2.3
  flutter_gif: ^0.0.4
  expandable_page_view: ^1.0.17
  barcode_widget: ^2.0.1
  flutter_countdown_timer: ^4.1.0
  qr_code_scanner: ^1.0.1
  intl: ^0.18.0
  flutter_screenutil: ^5.6.1
  synchronized: ^3.1.0
  provider: ^5.0.0
  injectable: ^2.1.2
  dio: ^5.1.2
  logger: ^1.4.0
  flutter_bloc: ^7.1.0
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  pin_code_fields: ^7.4.0
  event_bus: ^2.0.0
  build_runner: ^2.4.3
  fluttertoast: ^8.2.2
  shared_preferences: ^2.1.1
  rxdart: ^0.27.7
  intl_translation: ^0.18.0
  flutter_localization: ^0.1.11
  retrofit: ^4.0.1
  injectable_generator: ^2.1.5
  retrofit_generator: ^7.0.0
  flutter_smart_dialog: ^4.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_font_icons: ^2.2.5
  json_serializable: ^6.6.2

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
  fonts:
    - family: SVN-Gotham
      fonts:
        - asset: assets/fonts/SVN-Gotham Black.otf
        - asset: assets/fonts/SVN-Gotham Bold.otf
        - asset: assets/fonts/SVN-Gotham Italic.otf
        - asset: assets/fonts/SVN-Gotham Regular.otf

    - family: SVN-Days
      fonts:
        - asset: assets/fonts/SVN-Days.otf
